# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import flaui_pb2 as flaui__pb2


class FlaRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Launch = channel.unary_unary(
                '/flarpc.FlaRPC/Launch',
                request_serializer=flaui__pb2.Application.SerializeToString,
                response_deserializer=flaui__pb2.Application.FromString,
                )
        self.TestTypeText = channel.unary_unary(
                '/flarpc.FlaRPC/TestTypeText',
                request_serializer=flaui__pb2.TypeTextObject.SerializeToString,
                response_deserializer=flaui__pb2.TypeTextObject.FromString,
                )


class FlaRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Launch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestTypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlaRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Launch': grpc.unary_unary_rpc_method_handler(
                    servicer.Launch,
                    request_deserializer=flaui__pb2.Application.FromString,
                    response_serializer=flaui__pb2.Application.SerializeToString,
            ),
            'TestTypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TestTypeText,
                    request_deserializer=flaui__pb2.TypeTextObject.FromString,
                    response_serializer=flaui__pb2.TypeTextObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flarpc.FlaRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlaRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Launch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flarpc.FlaRPC/Launch',
            flaui__pb2.Application.SerializeToString,
            flaui__pb2.Application.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestTypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/flarpc.FlaRPC/TestTypeText',
            flaui__pb2.TypeTextObject.SerializeToString,
            flaui__pb2.TypeTextObject.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
