# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flaui.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='flaui.proto',
  package='flarpc',
  syntax='proto3',
  serialized_options=b'\252\002\006Server',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x66laui.proto\x12\x06\x66larpc\"\x07\n\x05\x45mpty\"9\n\x03\x41pp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x65xe_path\x18\x03 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\x05\"\x16\n\x04\x46ile\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"3\n\x0bTypeRequest\x12\x16\n\x02\x62y\x18\x01 \x01(\x0b\x32\n.flarpc.By\x12\x0c\n\x04text\x18\x02 \x01(\t\"b\n\x02\x42y\x12\x15\n\rautomation_id\x18\x01 \x01(\t\x12\r\n\x05xpath\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontrol_type\x18\x04 \x01(\t\x12\x12\n\nclass_name\x18\x05 \x01(\t\"s\n\x07\x45lement\x12\x15\n\rautomation_id\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12)\n\x0c\x63ontrol_type\x18\x03 \x01(\x0e\x32\x13.flarpc.ControlType\x12\x12\n\nfill_color\x18\x04 \x01(\x05\"#\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01*5\n\x0b\x43ontrolType\x12\n\n\x06\x42UTTON\x10\x00\x12\x0c\n\x08\x43HECKBOX\x10\x01\x12\x0c\n\x08\x43OMBOBOX\x10\x02\x32\xd3\x02\n\x06\x46laRPC\x12\"\n\x06Launch\x12\x0b.flarpc.App\x1a\x0b.flarpc.App\x12!\n\x05\x43lose\x12\x0b.flarpc.App\x1a\x0b.flarpc.App\x12\x30\n\x04Type\x12\x13.flarpc.TypeRequest\x1a\x13.flarpc.TypeRequest\x12*\n\x0b\x46indElement\x12\n.flarpc.By\x1a\x0f.flarpc.Element\x12\"\n\x05\x43lick\x12\n.flarpc.By\x1a\r.flarpc.Empty\x12\x31\n\x0b\x43lickCoords\x12\x13.flarpc.Coordinates\x1a\r.flarpc.Empty\x12\"\n\x06\x41ttach\x12\x0b.flarpc.App\x1a\x0b.flarpc.App\x12)\n\nScreenshot\x12\r.flarpc.Empty\x1a\x0c.flarpc.FileB\t\xaa\x02\x06Serverb\x06proto3'
)

_CONTROLTYPE = _descriptor.EnumDescriptor(
  name='ControlType',
  full_name='flarpc.ControlType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUTTON', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECKBOX', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMBOBOX', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=422,
  serialized_end=475,
)
_sym_db.RegisterEnumDescriptor(_CONTROLTYPE)

ControlType = enum_type_wrapper.EnumTypeWrapper(_CONTROLTYPE)
BUTTON = 0
CHECKBOX = 1
COMBOBOX = 2



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='flarpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=30,
)


_APP = _descriptor.Descriptor(
  name='App',
  full_name='flarpc.App',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='flarpc.App.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exe_path', full_name='flarpc.App.exe_path', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='flarpc.App.process_id', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=89,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='flarpc.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='flarpc.File.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=113,
)


_TYPEREQUEST = _descriptor.Descriptor(
  name='TypeRequest',
  full_name='flarpc.TypeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='by', full_name='flarpc.TypeRequest.by', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='flarpc.TypeRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=166,
)


_BY = _descriptor.Descriptor(
  name='By',
  full_name='flarpc.By',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='automation_id', full_name='flarpc.By.automation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xpath', full_name='flarpc.By.xpath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='flarpc.By.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control_type', full_name='flarpc.By.control_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_name', full_name='flarpc.By.class_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=266,
)


_ELEMENT = _descriptor.Descriptor(
  name='Element',
  full_name='flarpc.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='automation_id', full_name='flarpc.Element.automation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_name', full_name='flarpc.Element.class_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control_type', full_name='flarpc.Element.control_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fill_color', full_name='flarpc.Element.fill_color', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=383,
)


_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='flarpc.Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='flarpc.Coordinates.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='flarpc.Coordinates.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=420,
)

_TYPEREQUEST.fields_by_name['by'].message_type = _BY
_ELEMENT.fields_by_name['control_type'].enum_type = _CONTROLTYPE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['App'] = _APP
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['TypeRequest'] = _TYPEREQUEST
DESCRIPTOR.message_types_by_name['By'] = _BY
DESCRIPTOR.message_types_by_name['Element'] = _ELEMENT
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.enum_types_by_name['ControlType'] = _CONTROLTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

App = _reflection.GeneratedProtocolMessageType('App', (_message.Message,), {
  'DESCRIPTOR' : _APP,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.App)
  })
_sym_db.RegisterMessage(App)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.File)
  })
_sym_db.RegisterMessage(File)

TypeRequest = _reflection.GeneratedProtocolMessageType('TypeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TYPEREQUEST,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.TypeRequest)
  })
_sym_db.RegisterMessage(TypeRequest)

By = _reflection.GeneratedProtocolMessageType('By', (_message.Message,), {
  'DESCRIPTOR' : _BY,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.By)
  })
_sym_db.RegisterMessage(By)

Element = _reflection.GeneratedProtocolMessageType('Element', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENT,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.Element)
  })
_sym_db.RegisterMessage(Element)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATES,
  '__module__' : 'flaui_pb2'
  # @@protoc_insertion_point(class_scope:flarpc.Coordinates)
  })
_sym_db.RegisterMessage(Coordinates)


DESCRIPTOR._options = None

_FLARPC = _descriptor.ServiceDescriptor(
  name='FlaRPC',
  full_name='flarpc.FlaRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=478,
  serialized_end=817,
  methods=[
  _descriptor.MethodDescriptor(
    name='Launch',
    full_name='flarpc.FlaRPC.Launch',
    index=0,
    containing_service=None,
    input_type=_APP,
    output_type=_APP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='flarpc.FlaRPC.Close',
    index=1,
    containing_service=None,
    input_type=_APP,
    output_type=_APP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Type',
    full_name='flarpc.FlaRPC.Type',
    index=2,
    containing_service=None,
    input_type=_TYPEREQUEST,
    output_type=_TYPEREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindElement',
    full_name='flarpc.FlaRPC.FindElement',
    index=3,
    containing_service=None,
    input_type=_BY,
    output_type=_ELEMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Click',
    full_name='flarpc.FlaRPC.Click',
    index=4,
    containing_service=None,
    input_type=_BY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClickCoords',
    full_name='flarpc.FlaRPC.ClickCoords',
    index=5,
    containing_service=None,
    input_type=_COORDINATES,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Attach',
    full_name='flarpc.FlaRPC.Attach',
    index=6,
    containing_service=None,
    input_type=_APP,
    output_type=_APP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Screenshot',
    full_name='flarpc.FlaRPC.Screenshot',
    index=7,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_FILE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLARPC)

DESCRIPTOR.services_by_name['FlaRPC'] = _FLARPC

# @@protoc_insertion_point(module_scope)
